import { v4 as uuidv4 } from "uuid";

export const defaultForm = [
  {
    id: uuidv4(),
    lastChange: false,
    isChanging: false,
    change: false,
    className: "hidden",
    name: "Имя",
    value: "",
    hasChanges: false,
  },
  {
    id: uuidv4(),
    lastChange: false,
    isChanging: false,
    change: false,
    className: "hidden",
    name: "Фамилия",
    value: "",
    hasChanges: false,
  },
  {
    id: uuidv4(),
    lastChange: false,
    isChanging: false,
    change: false,
    className: "hidden",
    name: "Номер",
    value: "",
    hasChanges: false,
  },
  {
    id: uuidv4(),
    lastChange: false,
    isChanging: false,
    change: false,
    className: "hidden",
    name: "e-mail",
    value: "",
    hasChanges: false,
  },
  {
    id: uuidv4(),
    lastChange: false,
    isChanging: false,
    change: false,
    className: "hidden",
    name: "телеграм",
    value: "",
    hasChanges: false,
  },
  {
    id: uuidv4(),
    lastChange: false,
    isChanging: false,
    change: false,
    className: "hidden",
    name: "github",
    value: "",
    hasChanges: false,
  },
  {
    id: uuidv4(),
    lastChange: false,
    isChanging: false,
    change: false,
    className: "hidden",
    name: "skype",
    value: "",
    hasChanges: false,
  },
];

console.log("   gde fwe3w     ".trim());